name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # 或是你目前的分支名稱

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: web_app/package-lock.json

      - name: Install Dependencies 🔧
        run: npm install
        working-directory: web_app

      - name: Generate Static Site 🏗️
        run: npm run generate
        working-directory: web_app
        env:
          NUXT_PUBLIC_API_BASE_URL: ${{ secrets.NUXT_PUBLIC_API_BASE_URL }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web_app/.output/public
          branch: gh-pages # 部署到的分支
